/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactDto {
  email: string;
  firstName: string;
  iban: string;
  id?: number;
  lastName: string;
  userId?: number;
}
